name: Release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create GitHub release
        run: gh release create --generate-notes "$(gh release view --json name | jq .name | xargs bin/next_version)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Check version number
        run: |
          git tag
          python3 -m pip install setuptools_scm
          python3 -m setuptools_scm --help
      - name: Build and publish pypi.org release
        run: |
          python3 -m pip install --upgrade build twine
          python3 -m build
          python3 -m twine upload --verbose dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_NONINTERACTIVE: true
